name: Run Sellsy-Airtable Integration

on:
  schedule:
    - cron: '*/5 * * * *'  # Toutes les 5 minutes
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Mise en cache des dépendances pour accélérer

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install sellsy-api  # Installation manuelle pour s'assurer de l'installation du package

      - name: Vérification de la version de Python
        run: python --version

      - name: Vérification des modules installés
        run: |
          pip list
          python -c "import sys; print('Python Path:', sys.path)"
        continue-on-error: true  # Continue même si cette étape échoue

      - name: Run integration script
        env:
          SELLSY_CONSUMER_TOKEN: ${{ secrets.SELLSY_CONSUMER_TOKEN }}
          SELLSY_CONSUMER_SECRET: ${{ secrets.SELLSY_CONSUMER_SECRET }}
          SELLSY_USER_TOKEN: ${{ secrets.SELLSY_USER_TOKEN }}
          SELLSY_USER_SECRET: ${{ secrets.SELLSY_USER_SECRET }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: python main.py

      - name: Finalisation
        run: echo "Script terminé avec succès ✅"
